name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the Docker image
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/vicblog/mjapp:latest
          docker push registry.cn-hangzhou.aliyuncs.com/vicblog/mjapp:latest
